### ISSUE TITLE
Direct interfacing with raspberry pi/jetson nano

### ISSUE THREAD

**Issue by hoalarious** [Paulie-P/SonarInterface#3]
Hey Paulie,

Thanks for providing the python implementation.

I am just wondering if you know whether it's possible to directly interface (not using wifi) a t100/t200 with a raspberry pi/jetson nano and would I be able to power it on say once every 5 mins to take a reading and shut off to save power?

I am planning to attach it to an unmanned surface vehicle and need to keep the power consumption to a minimum.

Cheers,

**Comment by Hommus** [comment]
Hi @hoalarious,
I haven't opened the sonar devices but I imagine you would be able to create a direct interface, with enough effort. Good luck with your project!

**Comment by hoalarious** [comment]
@Paulie-P haha yeah that's what I'm worried about. Thanks though.
